# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: Karim Ashraf CI/CD 
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      # Change this, as applicable to you      
      KeyName: Ansible_keypair
      # Change this, as applicable to you
      ImageId: 'ami-09a41e26df464c548' 
      InstanceType: t2.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 