# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  error-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: return 1
    
  fail-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: 
          command: echo hello error
          when: on_fail

      

workflows:
  say-hello-workflow:
    jobs:
      - error-hello
      
