# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@2.0.3


jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file CloudFormation.yml \
                --stack-name myStack-KarimAshraf \
                --region us-east-1
    
  # configure-aws-CLI:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - run: 
  #         command: echo hello error
  #         when: on_fail

      

workflows:
 CircleCI-workflow:
    jobs:
      - create-infrastructure
      
