# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  save-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Hello World! by karim > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - "output.txt"
  print-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run: cat output.txt
      

workflows:
  say-hello-workflow:
    jobs:
      - save-hello
      - print-hello: 
           requires: 
             - save-hello
