# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  save-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Hello World! by karim > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - "output.txt"
  print-karim:
    docker:
      - image: cimg/base:stable
    steps:
      - run: cat output.txt
      - attach_workspace:
          at: .

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-karim: 
           requires: 
             - say-hello
