# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@2.0.3


jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file CloudFormation.yml \
                --stack-name myStack-KarimAshraf \
                --region us-east-1
    
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["ba:f7:9e:a1:12:ea:20:5d:11:da:bc:9e:3d:58:f5:05"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            (sleep 10; echo y;) | ansible-playbook -i inventory.txt main.yml

      

workflows:
 CircleCI-workflow:
    jobs:
      #- create-infrastructure
      - configure_infrastructure
      
